# Generated by Django 6.0.3 on 2026-03-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
