# Generated by Django 6.0.3 on 2026-03-16 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_scholar_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='solved',
            new_name='attempted',
        ),
    ]
