# Generated by Django 6.0.3 on 2026-03-16 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_solved_performance_attempted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='wrong',
        ),
    ]
