# Generated by Django 6.0.3 on 2026-03-16 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_performance_wrong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='correct_ratio',
        ),
    ]
