# Generated by Django 6.0.3 on 2026-03-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_profile_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Scholar',
        ),
    ]
