# Generated by Django 6.0.3 on 2026-03-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_wronganswer_question_answer_questionpage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpage',
            name='answer',
        ),
    ]
