# Generated by Django 6.0.3 on 2026-03-17 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_questionpage_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='page',
            field=models.ForeignKey(default=2026, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='base.questionpage'),
        ),
    ]
