# Generated by Django 6.0.3 on 2026-03-17 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_question_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='base.questionpage'),
        ),
    ]
