# Generated by Django 6.0.3 on 2026-03-17 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_question_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpage',
            name='year',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
