# Generated by Django 6.0.3 on 2026-03-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_question_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='full_explaination',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='hint',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
