# Generated by Django 6.0.3 on 2026-03-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='full_explaination',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='hint',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
