# Generated by Django 6.0.3 on 2026-03-20 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_question_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=50)),
                ('current_index', models.IntegerField(default=0)),
                ('status', models.CharField(default='in_progress', max_length=20)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.gamesession')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.questionpage')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='player_choices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='base.playerchoices'),
        ),
        migrations.AddField(
            model_name='question',
            name='player_choices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='base.playerchoices'),
        ),
        migrations.CreateModel(
            name='QuizPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.gamesession')),
            ],
        ),
        migrations.AddField(
            model_name='questionpage',
            name='quiz_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page', to='base.quizplan'),
        ),
    ]
