# Generated by Django 6.0.3 on 2026-03-20 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_gamesession_playerchoices_answer_player_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpage',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='base.subject'),
        ),
        migrations.AlterField(
            model_name='questionpage',
            name='quiz_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='base.quizplan'),
        ),
    ]
