# Generated by Django 6.0.3 on 2026-03-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_questionpage_subject_alter_questionpage_quiz_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpage',
            name='quiz_plan',
        ),
        migrations.AddField(
            model_name='questionpage',
            name='quiz_plans',
            field=models.ManyToManyField(related_name='pages', to='base.quizplan'),
        ),
    ]
