# Generated by Django 6.0.3 on 2026-03-21 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_questionpage_quiz_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerchoices',
            name='game_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_choices', to='base.gamesession'),
        ),
    ]
