# Generated by Django 6.0.3 on 2026-04-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_playerchoices_game_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
    ]
