# Generated by Django 6.0.3 on 2026-04-12 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_gamesession_correct_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizplan',
            name='game_session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_plan', to='base.gamesession'),
        ),
    ]
