# Generated by Django 6.0.6 on 2026-08-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_gamesession_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
